/**
 * Static legal and info pages — generated by build.mjs into /{slug}/index.html
 */
export const STATIC_PAGES = [
	{
		slug: 'about',
		name: 'About Us',
		title: 'About Us — Glow Magazine | Free Online Tools & Guides',
		desc: 'Learn about Glow Magazine — your destination for free online tools, calculators, converters and helpful articles on health, beauty, finance and everyday life.',
		body: `
<p>Glow Magazine is a free digital resource offering 50+ online tools, calculators and converters for health, beauty, women's health, nutrition, finance and everyday tasks. We believe useful tools should be fast, private and accessible to everyone — no sign-up required.</p>
<p>Alongside our tools, we publish articles and how-to guides to help you make informed decisions about wellness, productivity and daily life.</p>
<h2>Our mission</h2>
<p>Make professional-grade calculators and practical guides available to everyone, for free, on any device.</p>
<h2>What we offer</h2>
<ul>
<li>Free online calculators for BMI, calories, pregnancy, finance and more</li>
<li>Beauty and wellness quizzes and planners</li>
<li>Utility tools — QR codes, passwords, converters and counters</li>
<li>Blog articles, tips and how-to guides</li>
</ul>
<p>Have questions or feedback? Visit our <a href="/contact/">Contact</a> page — we would love to hear from you.</p>`,
	},
	{
		slug: 'contact',
		name: 'Contact',
		title: 'Contact Us — Glow Magazine',
		desc: 'Get in touch with the Glow Magazine team. Questions about our free tools, articles, partnerships or advertising — we are here to help.',
		body: `
<p>We welcome your questions, feedback and partnership enquiries. Choose the option that fits best below.</p>
<h2>General enquiries</h2>
<p>Email us at <a href="mailto:contact@glowmagazine.com">contact@glowmagazine.com</a>. We aim to respond within 2–3 business days.</p>
<h2>Editorial &amp; content</h2>
<p>For article corrections, guest post pitches or editorial questions, email <a href="mailto:editorial@glowmagazine.com">editorial@glowmagazine.com</a>.</p>
<h2>Advertising</h2>
<p>For advertising and sponsorship opportunities, email <a href="mailto:ads@glowmagazine.com">ads@glowmagazine.com</a>.</p>
<h2>Before you write</h2>
<p>Our tools run entirely in your browser — we do not store your calculator inputs. For privacy-related requests, see our <a href="/privacy-policy/">Privacy Policy</a>.</p>`,
	},
	{
		slug: 'privacy-policy',
		name: 'Privacy Policy',
		title: 'Privacy Policy — Glow Magazine',
		desc: 'How Glow Magazine collects, uses and protects your information when you use our free online tools and read our articles.',
		body: `
<p><strong>Last updated:</strong> June 30, 2026</p>
<p>Glow Magazine ("we", "us", "our") operates glowmagazine.com. This Privacy Policy explains how we handle information when you visit our website and use our free tools.</p>
<h2>Information we collect</h2>
<p><strong>Tool usage:</strong> Our calculators and converters run in your browser. We do not collect or store the numbers, text or personal data you enter into our tools unless a specific tool page states otherwise.</p>
<p><strong>Automatically collected data:</strong> Like most websites, we may collect standard log data (IP address, browser type, pages visited, referring URL) through our hosting and analytics providers.</p>
<p><strong>Newsletter:</strong> If you subscribe to our newsletter, we collect the email address you provide.</p>
<h2>Cookies &amp; advertising</h2>
<p>We may use cookies for essential site functionality, analytics and advertising (including Google AdSense). See our <a href="/cookie-policy/">Cookie Policy</a> for details and how to manage preferences.</p>
<h2>How we use information</h2>
<ul>
<li>Operate and improve our website and tools</li>
<li>Understand traffic and usage patterns</li>
<li>Send newsletters you have opted into</li>
<li>Display relevant advertisements</li>
<li>Respond to enquiries</li>
</ul>
<h2>Third-party services</h2>
<p>We use third-party services such as hosting (Vercel), analytics and advertising networks. These providers have their own privacy policies governing their use of data.</p>
<h2>Your rights</h2>
<p>Depending on your location, you may have rights to access, correct or delete personal data we hold. Contact us at <a href="mailto:contact@glowmagazine.com">contact@glowmagazine.com</a>.</p>
<h2>Children</h2>
<p>Our site is not directed at children under 13. We do not knowingly collect personal information from children.</p>
<h2>Changes</h2>
<p>We may update this policy from time to time. Continued use of the site after changes constitutes acceptance of the updated policy.</p>`,
	},
	{
		slug: 'disclaimer',
		name: 'Disclaimer',
		title: 'Disclaimer — Glow Magazine',
		desc: 'Important disclaimers for Glow Magazine free tools, calculators and articles. Not medical, financial or legal advice.',
		body: `
<p><strong>Last updated:</strong> June 30, 2026</p>
<h2>General information only</h2>
<p>Content on Glow Magazine — including articles, guides and tool results — is provided for general informational and educational purposes only. It is not a substitute for professional advice.</p>
<h2>Not medical advice</h2>
<p>Health, nutrition, pregnancy and women's health calculators and articles are not medical advice. Always consult a qualified healthcare provider before making health decisions. Do not disregard professional medical advice because of something you read on this site.</p>
<h2>Not financial or legal advice</h2>
<p>Finance calculators (EMI, loan, savings, currency) provide estimates only. Results may not reflect actual rates, fees or terms. Consult a licensed financial adviser or attorney for decisions affecting your finances or legal rights.</p>
<h2>Accuracy of tools</h2>
<p>We strive for accuracy but make no warranties that our tools are error-free, complete or suitable for any particular purpose. You use all tools at your own risk.</p>
<h2>External links</h2>
<p>Our site may link to third-party websites. We are not responsible for their content, privacy practices or availability.</p>
<h2>Affiliate &amp; advertising</h2>
<p>We may display advertisements and participate in affiliate programmes. This does not affect our editorial independence on informational content.</p>
<h2>Contact</h2>
<p>Questions about this disclaimer? Email <a href="mailto:contact@glowmagazine.com">contact@glowmagazine.com</a>.</p>`,
	},
	{
		slug: 'terms-of-use',
		name: 'Terms of Use',
		title: 'Terms of Use — Glow Magazine',
		desc: 'Terms and conditions for using Glow Magazine free online tools, calculators and website content.',
		body: `
<p><strong>Last updated:</strong> June 30, 2026</p>
<p>By accessing glowmagazine.com you agree to these Terms of Use. If you do not agree, please do not use the site.</p>
<h2>Use of the site</h2>
<p>You may use our free tools and read our content for personal, non-commercial purposes unless we give written permission otherwise. You may not scrape, copy, redistribute or resell our content or tools in bulk without permission.</p>
<h2>Intellectual property</h2>
<p>All site content, design, logos and tool implementations are owned by Glow Magazine or our licensors and protected by applicable copyright laws.</p>
<h2>Prohibited conduct</h2>
<ul>
<li>Attempting to disrupt or compromise site security</li>
<li>Using automated means to overload our servers</li>
<li>Misrepresenting affiliation with Glow Magazine</li>
<li>Using the site for unlawful purposes</li>
</ul>
<h2>Disclaimer of warranties</h2>
<p>The site and tools are provided "as is" without warranties of any kind. See our <a href="/disclaimer/">Disclaimer</a> for important limitations.</p>
<h2>Limitation of liability</h2>
<p>To the fullest extent permitted by law, Glow Magazine shall not be liable for any indirect, incidental or consequential damages arising from your use of the site.</p>
<h2>Changes</h2>
<p>We may modify these terms at any time. Your continued use constitutes acceptance of revised terms.</p>
<h2>Contact</h2>
<p><a href="/contact/">Contact us</a> with any questions about these terms.</p>`,
	},
	{
		slug: 'cookie-policy',
		name: 'Cookie Policy',
		title: 'Cookie Policy — Glow Magazine',
		desc: 'How Glow Magazine uses cookies and similar technologies on glowmagazine.com.',
		body: `
<p><strong>Last updated:</strong> June 30, 2026</p>
<p>This Cookie Policy explains how Glow Magazine uses cookies and similar technologies when you visit glowmagazine.com.</p>
<h2>What are cookies?</h2>
<p>Cookies are small text files stored on your device by your browser. They help websites remember preferences and understand how visitors use the site.</p>
<h2>How we use cookies</h2>
<ul>
<li><strong>Essential cookies</strong> — required for basic site functionality</li>
<li><strong>Analytics cookies</strong> — help us understand traffic and improve the site</li>
<li><strong>Advertising cookies</strong> — used by ad partners (e.g. Google AdSense) to show relevant ads and measure performance</li>
</ul>
<h2>Third-party cookies</h2>
<p>Advertising and analytics partners may set their own cookies when you visit our site. We do not control these cookies. Refer to Google's policies for AdSense-related cookies.</p>
<h2>Managing cookies</h2>
<p>You can control or delete cookies through your browser settings. Blocking cookies may affect site functionality. For Google ad personalisation, visit <a href="https://adssettings.google.com/" rel="noopener noreferrer" target="_blank">Google Ads Settings</a>.</p>
<h2>More information</h2>
<p>See our <a href="/privacy-policy/">Privacy Policy</a> for how we handle personal data. Questions? <a href="/contact/">Contact us</a>.</p>`,
	},
];
