/**
 * GlowMagazine — single source of truth for all tools.
 * Used by build.mjs to generate every tool page, the tools index, category
 * pages and the sitemap. Also drives on-page search (exported to tools-index.js).
 *
 * Each tool:
 *   slug      Clean URL segment -> /{slug}/
 *   name      Display name
 *   category  Category key (see CATEGORIES)
 *   icon      Material Symbols Outlined glyph name
 *   handler   Calculator module file under assets/js/tools/{handler}.js (omit if not built yet)
 *   title     <title> / SEO title (unique)
 *   meta      Meta description (unique, <=160 chars)
 *   intro     Paragraph under the H1
 *   faqs      [{ q, a }] -> FAQ section + FAQ schema
 */

export const SITE = {
	name: 'Glow Magazine',
	url: 'https://glowmagazine.com',
	tagline: 'All-in-One Free Tools Collection',
};

export const CATEGORIES = {
	health:          { name: 'Health',          icon: 'health_and_safety', blurb: 'Free health calculators — BMI, calories, water, BMR, TDEE and more.' },
	beauty:          { name: 'Beauty',           icon: 'styler',            blurb: 'Skin, hair, size and style tools to help you look and feel your best.' },
	'womens-health': { name: "Women's Health",   icon: 'pregnant_woman',    blurb: 'Period, ovulation, fertility and pregnancy calculators — private and instant.' },
	daily:           { name: 'Daily',            icon: 'wb_sunny',          blurb: 'Everyday tools — age, sleep, zodiac, love and numerology.' },
	nutrition:       { name: 'Nutrition',        icon: 'restaurant',        blurb: 'Daily protein, carb, fat and sugar targets plus meal planning.' },
	finance:         { name: 'Finance',          icon: 'payments',          blurb: 'EMI, loan, savings, tip and currency tools. Fast and accurate.' },
	utilities:       { name: 'Utilities',        icon: 'build',             blurb: 'QR codes, passwords, converters, counters and handy everyday utilities.' },
};

export const TOOLS = [
	/* ---------------- HEALTH ---------------- */
	{ slug: 'bmi-calculator', name: 'BMI Calculator', category: 'health', icon: 'fitness_center', handler: 'bmi',
	  title: 'BMI Calculator — Free Body Mass Index Calculator (Metric & Imperial)',
	  meta: 'Free BMI calculator. Enter your height and weight to instantly find your Body Mass Index and healthy weight range. Metric & imperial, no sign-up.',
	  intro: 'Calculate your Body Mass Index (BMI) in seconds. BMI is a quick screening number that uses your height and weight to estimate whether you are in a healthy weight range.',
	  faqs: [
		{ q: 'What is a healthy BMI range?', a: 'For most adults a BMI between 18.5 and 24.9 is considered healthy. Below 18.5 is underweight, 25–29.9 is overweight, and 30 or above is in the obese range.' },
		{ q: 'How is BMI calculated?', a: 'BMI = weight (kg) ÷ height (m)². In imperial units it is (pounds ÷ inches²) × 703. This calculator does the math for you in both unit systems.' },
		{ q: 'Is BMI accurate for everyone?', a: 'BMI is a useful general screening tool but it does not measure body fat directly. Very muscular people may read high, and it is not intended for children, pregnant women or athletes.' },
	  ] },
	{ slug: 'calorie-calculator', name: 'Calorie Calculator', category: 'health', icon: 'local_fire_department', handler: 'calorie',
	  title: 'Calorie Calculator — Daily Calorie Needs for Weight Loss & Maintenance',
	  meta: 'Free calorie calculator. Find how many calories you need each day to lose, maintain or gain weight based on your age, sex, height, weight and activity.',
	  intro: 'Find your daily calorie needs based on your age, sex, height, weight and activity level — plus targets for losing, maintaining or gaining weight.',
	  faqs: [
		{ q: 'How many calories should I eat to lose weight?', a: 'A safe deficit of about 500 calories below your maintenance level leads to roughly 0.45 kg (1 lb) of weight loss per week. This tool shows that target for you.' },
		{ q: 'What is maintenance calories?', a: 'Maintenance is the number of calories that keeps your weight stable — your total daily energy expenditure (TDEE).' },
	  ] },
	{ slug: 'water-intake-calculator', name: 'Water Intake Calculator', category: 'health', icon: 'water_drop', handler: 'water',
	  title: 'Water Intake Calculator — How Much Water Should You Drink a Day?',
	  meta: 'Free water intake calculator. Find your recommended daily water intake in litres and glasses based on your weight, activity level and climate.',
	  intro: 'Find how much water you should drink each day, in litres and glasses, based on your body weight and activity level.',
	  faqs: [
		{ q: 'How much water should I drink daily?', a: 'A common guideline is about 30–35 ml per kg of body weight, with more on active or hot days. This tool estimates your personal target.' },
	  ] },
	{ slug: 'bmr-calculator', name: 'BMR Calculator', category: 'health', icon: 'cardiology', handler: 'bmr',
	  title: 'BMR Calculator — Basal Metabolic Rate (Calories at Rest)',
	  meta: 'Free BMR calculator using the Mifflin-St Jeor equation. Find how many calories your body burns at rest each day.',
	  intro: 'Calculate your Basal Metabolic Rate (BMR) — the calories your body burns at complete rest — using the accurate Mifflin-St Jeor equation.',
	  faqs: [ { q: 'What is BMR?', a: 'BMR is the number of calories your body needs to perform basic life-sustaining functions at rest, such as breathing and circulation.' } ] },
	{ slug: 'tdee-calculator', name: 'TDEE Calculator', category: 'health', icon: 'monitoring', handler: 'tdee',
	  title: 'TDEE Calculator — Total Daily Energy Expenditure',
	  meta: 'Free TDEE calculator. Find your total daily energy expenditure (maintenance calories) from your BMR and activity level.',
	  intro: 'Calculate your Total Daily Energy Expenditure (TDEE) — the total calories you burn per day including activity. This is your maintenance calorie level.',
	  faqs: [ { q: 'How is TDEE different from BMR?', a: 'BMR is calories burned at rest; TDEE multiplies BMR by an activity factor to include movement and exercise.' } ] },
	{ slug: 'macro-calculator', name: 'Macro Calculator', category: 'health', icon: 'pie_chart', handler: 'macro',
	  title: 'Macro Calculator — Daily Protein, Carbs & Fat Split',
	  meta: 'Free macronutrient calculator. Get your daily protein, carb and fat targets in grams based on your goal and calorie needs.',
	  intro: 'Get your daily protein, carbohydrate and fat targets in grams, balanced for your calorie needs and goal.' },
	{ slug: 'body-fat-calculator', name: 'Body Fat Calculator', category: 'health', icon: 'straighten', handler: 'bodyfat',
	  title: 'Body Fat Calculator — Estimate Body Fat % (US Navy Method)',
	  meta: 'Free body fat percentage calculator using the U.S. Navy tape method. Estimate your body fat from a few simple measurements.',
	  intro: 'Estimate your body fat percentage using the U.S. Navy tape method from a few simple measurements.' },
	{ slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', category: 'health', icon: 'target', handler: 'ideal-weight',
	  title: "Ideal Weight Calculator — Healthy Weight for Your Height",
	  meta: 'Free ideal weight calculator. Find your healthy target weight range for your height using proven formulas (Devine, Robinson, BMI).',
	  intro: 'Find your ideal body weight for your height and sex using several proven formulas, plus a healthy BMI-based range.',
	  faqs: [ { q: 'Which ideal weight formula is best?', a: 'No single formula is perfect. We show Devine, Robinson and Miller results plus a healthy BMI range so you can see a sensible target band.' } ] },
	{ slug: 'pregnancy-due-date-calculator', name: 'Pregnancy Due Date Calculator', category: 'health', icon: 'pregnant_woman', handler: 'duedate',
	  title: "Pregnancy Due Date Calculator — Estimate Your Baby's Due Date",
	  meta: "Free due date calculator. Estimate your baby's due date from your last period or conception date, plus your current pregnancy week.",
	  intro: "Estimate your baby's due date from the first day of your last period, plus see how many weeks pregnant you are now.",
	  faqs: [ { q: 'How is the due date calculated?', a: "The standard estimate (Naegele's rule) adds 280 days (40 weeks) to the first day of your last menstrual period." } ] },

	/* ---------------- BEAUTY ---------------- */
	{ slug: 'skin-type-quiz', name: 'Skin Type Quiz', category: 'beauty', icon: 'face_retouching_natural', handler: 'skin-type',
	  title: 'Skin Type Quiz — Find Your Skin Type (Oily, Dry, Combination)',
	  meta: 'Free skin type quiz. Answer a few questions to discover whether your skin is oily, dry, combination, normal or sensitive — with care tips.',
	  intro: 'Answer a few quick questions to discover your skin type and get tailored care tips.' },
	{ slug: 'hair-type-quiz', name: 'Hair Type Quiz', category: 'beauty', icon: 'content_cut', handler: 'hair-type',
	  title: 'Hair Type Quiz — Discover Your Hair Type & Curl Pattern',
	  meta: 'Free hair type quiz. Find your hair type and curl pattern (straight, wavy, curly, coily) and get tailored hair-care tips.',
	  intro: 'Find your hair type and curl pattern, and get care tips that actually suit your hair.' },
	{ slug: 'makeup-shade-finder', name: 'Makeup Shade Finder', category: 'beauty', icon: 'palette', handler: 'makeup-shade',
	  title: 'Makeup Shade Finder — Match Your Foundation Shade',
	  meta: 'Free makeup shade finder. Match your perfect foundation shade and undertone with a quick guided quiz.',
	  intro: 'Match your perfect foundation shade and undertone with a quick guided quiz.' },
	{ slug: 'face-shape-detector', name: 'Face Shape Detector', category: 'beauty', icon: 'sentiment_satisfied', handler: 'face-shape',
	  title: 'Face Shape Detector — Find Your Face Shape',
	  meta: 'Free face shape detector. Discover whether your face is oval, round, square, heart or oblong and get hairstyle & glasses tips.',
	  intro: 'Discover your face shape and get hairstyle and glasses recommendations that flatter it.' },
	{ slug: 'bra-size-calculator', name: 'Bra Size Calculator', category: 'beauty', icon: 'straighten', handler: 'bra-size',
	  title: 'Bra Size Calculator — Find Your True Bra Size',
	  meta: 'Free bra size calculator. Enter your band and bust measurements to find your correct bra size in US, UK and EU sizing.',
	  intro: 'Find your correct bra size from your band and bust measurements, with US, UK and EU equivalents.' },
	{ slug: 'ring-size-calculator', name: 'Ring Size Calculator', category: 'beauty', icon: 'diamond', handler: 'ring-size',
	  title: 'Ring Size Calculator — Find Your Ring Size',
	  meta: 'Free ring size calculator. Convert finger circumference or diameter to US, UK and EU ring sizes.',
	  intro: 'Convert your finger circumference or diameter into US, UK and EU ring sizes.' },
	{ slug: 'hair-color-matcher', name: 'Hair Color Matcher', category: 'beauty', icon: 'colorize', handler: 'hair-color',
	  title: 'Hair Color Matcher — Best Hair Color for Your Skin Tone',
	  meta: 'Free hair color matcher. Find flattering hair colours for your skin tone and undertone with a quick quiz.',
	  intro: 'Find flattering hair colours for your skin tone and undertone.' },
	{ slug: 'skincare-routine-builder', name: 'Skincare Routine Builder', category: 'beauty', icon: 'spa', handler: 'skincare',
	  title: 'Skincare Routine Builder — Build Your AM & PM Routine',
	  meta: 'Free skincare routine builder. Get a step-by-step morning and night routine tailored to your skin type and concerns.',
	  intro: 'Build a step-by-step morning and night skincare routine tailored to your skin type and concerns.' },

	/* ---------------- WOMEN'S HEALTH ---------------- */
	{ slug: 'period-calculator', name: 'Period Calculator', category: 'womens-health', icon: 'calendar_month', handler: 'period',
	  title: 'Period Calculator — Predict Your Next Period',
	  meta: 'Free period calculator. Predict your next period dates and track your cycle from your last period and average cycle length.',
	  intro: 'Predict your next few periods from the date of your last period and your average cycle length.',
	  faqs: [ { q: 'How accurate is a period prediction?', a: 'Predictions assume a regular cycle. If your cycle varies a lot, treat the dates as an estimate.' } ] },
	{ slug: 'ovulation-calculator', name: 'Ovulation Calculator', category: 'womens-health', icon: 'egg', handler: 'ovulation',
	  title: 'Ovulation Calculator — Find Your Most Fertile Days',
	  meta: 'Free ovulation calculator. Estimate your ovulation date and most fertile days to help plan or prevent pregnancy.',
	  intro: 'Estimate your ovulation date and most fertile window from your last period and cycle length.' },
	{ slug: 'fertility-window-calculator', name: 'Fertility Window Calculator', category: 'womens-health', icon: 'spa', handler: 'fertility',
	  title: 'Fertility Window Calculator — Your Best Days to Conceive',
	  meta: 'Free fertility window calculator. Find your fertile window and peak conception days based on your cycle.',
	  intro: 'Find your fertile window and peak conception days based on your cycle.' },
	{ slug: 'pregnancy-week-calculator', name: 'Pregnancy Week Calculator', category: 'womens-health', icon: 'child_friendly', handler: 'pregnancy-week',
	  title: 'Pregnancy Week Calculator — How Many Weeks Pregnant Am I?',
	  meta: 'Free pregnancy week calculator. Find out how many weeks and days pregnant you are and which trimester you are in.',
	  intro: 'Find out how many weeks and days pregnant you are, and which trimester you are in.' },
	{ slug: 'pregnancy-weight-gain-calculator', name: 'Pregnancy Weight Gain Calculator', category: 'womens-health', icon: 'monitor_weight', handler: 'pregnancy-weight',
	  title: 'Pregnancy Weight Gain Calculator — Healthy Gain by Week',
	  meta: 'Free pregnancy weight gain calculator. See your recommended healthy weight gain range based on pre-pregnancy BMI and week.',
	  intro: 'See your recommended healthy weight-gain range based on your pre-pregnancy BMI and current week.' },

	/* ---------------- DAILY ---------------- */
	{ slug: 'age-calculator', name: 'Age Calculator', category: 'daily', icon: 'cake', handler: 'age',
	  title: 'Age Calculator — Calculate Your Exact Age in Years, Months & Days',
	  meta: 'Free age calculator. Enter your date of birth to find your exact age in years, months, days, hours — plus days until your next birthday.',
	  intro: 'Find your exact age in years, months and days from your date of birth. See your total days lived and a countdown to your next birthday.',
	  faqs: [
		{ q: 'How does the age calculator work?', a: 'Enter your date of birth and an optional target date. The tool counts the precise years, months and days between the two, accounting for leap years.' },
		{ q: 'Can I calculate age on a future or past date?', a: 'Yes — change the "age at date" field to any date and the calculator shows how old you were, or will be, on that day.' },
	  ] },
	{ slug: 'sleep-calculator', name: 'Sleep Calculator', category: 'daily', icon: 'bedtime', handler: 'sleep',
	  title: 'Sleep Calculator — Best Bedtime & Wake-Up Times',
	  meta: 'Free sleep calculator. Find the best times to go to bed or wake up based on 90-minute sleep cycles so you wake refreshed.',
	  intro: 'Find the best bedtime or wake-up times based on 90-minute sleep cycles, so you wake up refreshed instead of groggy.',
	  faqs: [ { q: 'Why 90-minute cycles?', a: 'A full sleep cycle averages about 90 minutes. Waking at the end of a cycle, rather than mid-cycle, helps you feel more rested.' } ] },
	{ slug: 'zodiac-sign-calculator', name: 'Zodiac Sign Calculator', category: 'daily', icon: 'stars', handler: 'zodiac',
	  title: 'Zodiac Sign Calculator — Find Your Star Sign by Birth Date',
	  meta: 'Free zodiac sign calculator. Enter your birth date to find your astrological star sign, element and key traits.',
	  intro: 'Enter your birth date to find your zodiac star sign, its element and key personality traits.' },
	{ slug: 'love-calculator', name: 'Love Calculator', category: 'daily', icon: 'favorite', handler: 'love',
	  title: 'Love Calculator — Fun Love Compatibility Test',
	  meta: 'Free love calculator. Enter two names for a fun love-compatibility percentage. Just for entertainment!',
	  intro: 'Enter two names for a fun love-compatibility score. Just for entertainment — not a scientific measure!' },
	{ slug: 'name-numerology-calculator', name: 'Name Numerology Calculator', category: 'daily', icon: 'pin', handler: 'numerology',
	  title: 'Name Numerology Calculator — Your Destiny Number',
	  meta: 'Free name numerology calculator. Find your destiny number and its meaning from the letters in your name.',
	  intro: 'Find your destiny number and its meaning from the letters in your name.' },

	/* ---------------- NUTRITION ---------------- */
	{ slug: 'protein-intake-calculator', name: 'Protein Intake Calculator', category: 'nutrition', icon: 'egg_alt', handler: 'protein',
	  title: 'Protein Intake Calculator — Daily Protein Needs (grams)',
	  meta: 'Free protein intake calculator. Find how many grams of protein you need each day based on your weight, activity and goal.',
	  intro: 'Find how many grams of protein you need each day based on your weight, activity level and goal.' },
	{ slug: 'carb-intake-calculator', name: 'Carb Intake Calculator', category: 'nutrition', icon: 'bakery_dining', handler: 'carb',
	  title: 'Carb Intake Calculator — Daily Carbohydrate Needs',
	  meta: 'Free carb intake calculator. Find your recommended daily carbohydrate intake in grams for your calorie target and goal.',
	  intro: 'Find your recommended daily carbohydrate intake in grams for your calorie target and goal.' },
	{ slug: 'fat-intake-calculator', name: 'Fat Intake Calculator', category: 'nutrition', icon: 'lunch_dining', handler: 'fat',
	  title: 'Fat Intake Calculator — Daily Healthy Fat Needs',
	  meta: 'Free fat intake calculator. Find your recommended daily fat intake in grams based on your calories and goal.',
	  intro: 'Find your recommended daily fat intake in grams based on your calories and goal.' },
	{ slug: 'sugar-intake-calculator', name: 'Sugar Intake Calculator', category: 'nutrition', icon: 'icecream', handler: 'sugar',
	  title: 'Sugar Intake Calculator — Daily Added Sugar Limit',
	  meta: 'Free sugar intake calculator. See your recommended daily added-sugar limit in grams and teaspoons per health guidelines.',
	  intro: 'See your recommended daily added-sugar limit in grams and teaspoons, per major health guidelines.' },
	{ slug: 'meal-planner', name: 'Meal Planner', category: 'nutrition', icon: 'menu_book', handler: 'meal-planner',
	  title: 'Meal Planner — Build a Balanced Daily Meal Plan',
	  meta: 'Free meal planner. Split your daily calories across meals and balance protein, carbs and fat for your goal.',
	  intro: 'Split your daily calories across meals and balance protein, carbs and fat for your goal.' },

	/* ---------------- FINANCE ---------------- */
	{ slug: 'emi-calculator', name: 'EMI Calculator', category: 'finance', icon: 'account_balance', handler: 'emi',
	  title: 'EMI Calculator — Monthly Loan Instalment Calculator',
	  meta: 'Free EMI calculator. Calculate your monthly loan instalment, total interest and total payment for any loan amount, rate and tenure.',
	  intro: 'Calculate your monthly loan instalment (EMI), total interest and total payment for any loan amount, interest rate and tenure.',
	  faqs: [ { q: 'What is EMI?', a: 'EMI (Equated Monthly Instalment) is the fixed amount you pay each month to repay a loan, covering both principal and interest.' } ] },
	{ slug: 'loan-calculator', name: 'Loan Calculator', category: 'finance', icon: 'request_quote', handler: 'loan',
	  title: 'Loan Calculator — Repayment, Interest & Total Cost',
	  meta: 'Free loan calculator. See your monthly repayment, total interest and total cost for any loan amount, rate and term.',
	  intro: 'See your monthly repayment, total interest and total cost for any loan amount, rate and term.' },
	{ slug: 'savings-calculator', name: 'Savings Calculator', category: 'finance', icon: 'savings', handler: 'savings',
	  title: 'Savings Calculator — Compound Interest & Goal Planner',
	  meta: 'Free savings calculator. See how your savings grow with compound interest and regular monthly contributions over time.',
	  intro: 'See how your savings grow over time with compound interest and regular monthly contributions.' },
	{ slug: 'currency-converter', name: 'Currency Converter', category: 'finance', icon: 'currency_exchange', handler: 'currency',
	  title: 'Currency Converter — Live Exchange Rates for 150+ Currencies',
	  meta: 'Free currency converter with live exchange rates for 150+ currencies. Convert USD, EUR, GBP, INR, SGD and more instantly.',
	  intro: 'Convert between 150+ world currencies using live daily exchange rates. Enter an amount, pick your currencies, and get an instant conversion.',
	  faqs: [
		{ q: 'Where do the exchange rates come from?', a: 'Rates are fetched live from a public exchange-rate API and updated daily. They are mid-market reference rates — your bank may apply a slightly different rate plus fees.' },
		{ q: 'Is the currency converter free?', a: 'Yes, it is completely free with no sign-up required.' },
	  ] },
	{ slug: 'tip-calculator', name: 'Tip Calculator', category: 'finance', icon: 'receipt_long', handler: 'tip',
	  title: 'Tip Calculator — Tip Amount & Bill Split',
	  meta: 'Free tip calculator. Work out the tip and total, and split the bill evenly between any number of people.',
	  intro: 'Work out the tip and total for any bill, and split it evenly between any number of people.' },

	/* ---------------- UTILITIES ---------------- */
	{ slug: 'qr-code-generator', name: 'QR Code Generator', category: 'utilities', icon: 'qr_code_2', handler: 'qr',
	  title: 'QR Code Generator — Free Custom QR Codes (PNG Download)',
	  meta: 'Free QR code generator. Create QR codes for links, text, Wi-Fi, email and phone numbers, then download them as PNG. No sign-up.',
	  intro: 'Generate a QR code for any link, text, phone number or email in seconds, then download it as a high-resolution PNG image — completely free.',
	  faqs: [
		{ q: 'Are the QR codes free to use commercially?', a: 'Yes. The QR codes you generate are free to use anywhere, including on products, posters and packaging, with no expiry.' },
		{ q: 'Do the QR codes expire?', a: 'No. A QR code simply encodes your text or link, so it never expires as long as the destination stays active.' },
	  ] },
	{ slug: 'password-generator', name: 'Password Generator', category: 'utilities', icon: 'password', handler: 'password',
	  title: 'Password Generator — Free Strong, Secure Random Passwords',
	  meta: 'Free password generator. Create strong, random, secure passwords with custom length, symbols and numbers. Generated locally in your browser.',
	  intro: 'Create strong, random passwords that are hard to guess and easy to copy. Everything runs locally in your browser — your passwords are never sent anywhere.',
	  faqs: [
		{ q: 'Are the generated passwords safe?', a: 'Yes. Passwords are generated entirely in your browser using a cryptographically secure random source and are never transmitted or stored on any server.' },
	  ] },
	{ slug: 'unit-converter', name: 'Unit Converter', category: 'utilities', icon: 'swap_horiz', handler: 'unit',
	  title: 'Unit Converter — Length, Weight, Temperature & More',
	  meta: 'Free unit converter. Convert length, weight, temperature, area, volume and speed between metric and imperial units instantly.',
	  intro: 'Convert length, weight, temperature, volume and speed between metric and imperial units instantly.' },
	{ slug: 'percentage-calculator', name: 'Percentage Calculator', category: 'utilities', icon: 'percent', handler: 'percentage',
	  title: 'Percentage Calculator — Find Percentages Fast',
	  meta: 'Free percentage calculator. Find a percentage of a number, percentage change, and what percent one number is of another.',
	  intro: 'Quickly find a percentage of a number, what percent one number is of another, and percentage increase or decrease.' },
	{ slug: 'date-calculator', name: 'Date Calculator', category: 'utilities', icon: 'event', handler: 'date',
	  title: 'Date Calculator — Days Between Dates & Add/Subtract Days',
	  meta: 'Free date calculator. Find the number of days between two dates, or add and subtract days, weeks and months from any date.',
	  intro: 'Find the number of days between two dates, or add and subtract days, weeks and months from any date.' },
	{ slug: 'time-calculator', name: 'Time Calculator', category: 'utilities', icon: 'schedule', handler: 'time',
	  title: 'Time Calculator — Add & Subtract Hours and Minutes',
	  meta: 'Free time calculator. Add or subtract hours, minutes and seconds, and find the duration between two times.',
	  intro: 'Add or subtract hours, minutes and seconds, and find the duration between two times.' },
	{ slug: 'discount-calculator', name: 'Discount Calculator', category: 'utilities', icon: 'sell', handler: 'discount',
	  title: 'Discount Calculator — Sale Price & Savings',
	  meta: 'Free discount calculator. Find the final sale price and how much you save for any percentage discount.',
	  intro: 'Find the final sale price and exactly how much you save for any percentage discount.' },
	{ slug: 'random-number-generator', name: 'Random Number Generator', category: 'utilities', icon: 'casino', handler: 'random',
	  title: 'Random Number Generator — Pick Random Numbers',
	  meta: 'Free random number generator. Generate random numbers within any range, with or without duplicates.',
	  intro: 'Generate random numbers within any range, with or without duplicates.' },
	{ slug: 'word-counter', name: 'Word Counter', category: 'utilities', icon: 'article', handler: 'word-counter',
	  title: 'Word Counter — Free Word & Character Count Tool',
	  meta: 'Free word counter. Instantly count words, characters, sentences, paragraphs and estimated reading time as you type. No sign-up.',
	  intro: 'Paste or type your text to instantly count words, characters, sentences, paragraphs and estimated reading time. Everything updates live as you type.',
	  faqs: [
		{ q: 'Does the word counter store my text?', a: 'No. All counting happens in your browser. Your text is never uploaded or saved on any server.' },
	  ] },
	{ slug: 'text-case-converter', name: 'Text Case Converter', category: 'utilities', icon: 'text_fields', handler: 'textcase',
	  title: 'Text Case Converter — UPPERCASE, lowercase & Title Case',
	  meta: 'Free text case converter. Convert text to UPPERCASE, lowercase, Title Case, Sentence case and more in one click.',
	  intro: 'Convert your text to UPPERCASE, lowercase, Title Case, Sentence case and more in one click.' },
];
